# Generated by Django 5.0.1 on 2025-07-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coffe',
            new_name='Coffee',
        ),
    ]
